name: Validate docker images

on:
  push:
    branches:
    - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest 
    container: ghcr.io/pytorch/pytorch:2.2.2-cuda11.8-cudnn8-devel
    steps:
      - uses: actions/checkout@v3  
      - name: Run smoke tests
        run:  python test/smoke_test/smoke_test.py --package torchonly --runtime-error-check enabled

  
